
import React, { useState, useRef, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { 
  Camera, Activity, AlertTriangle, CheckCircle, 
  ArrowLeft, Mic, Search, ChevronRight, Thermometer, Brain, 
  Wind, Info, ShieldCheck, Sparkles, Clock, MapPin, Download, Share2,
  Stethoscope, Pill, BookOpen, Navigation, Smile, Phone, MessageSquare, Send, Image as ImageIcon,
  Zap,
  Leaf,
  ScanFace,
  Heart
} from 'lucide-react';
import { analyzeSymptoms, analyzeWound, analyzeMood, chatWithMedi, checkEmergencyKeywords } from '../services/geminiService';
import { SymptomAnalysis, WoundAnalysis, MoodAnalysis, ChatMessage } from '../types';

// --- Shared Components ---
const LoadingOverlay: React.FC<{ text: string }> = ({ text }) => (
  <div className="fixed inset-0 bg-white/95 dark:bg-slate-900/95 z-[100] flex flex-col items-center justify-center backdrop-blur-xl transition-colors">
    <div className="relative mb-8">
      <div className="w-20 h-20 border-4 border-blue-100 dark:border-slate-700 border-t-blue-600 dark:border-t-blue-500 rounded-[30px] animate-spin"></div>
      <div className="absolute inset-0 flex items-center justify-center">
        <Sparkles size={28} className="text-blue-500 animate-pulse" />
      </div>
    </div>
    <p className="text-slate-900 dark:text-white font-black text-xl mb-1 tracking-tight">{text}</p>
    <p className="text-slate-400 dark:text-slate-500 text-xs font-bold uppercase tracking-[0.2em] animate-pulse">Consulting Gemini Bio-AI</p>
  </div>
);

const EmergencyOverlay: React.FC<{ onDismiss: () => void }> = ({ onDismiss }) => (
  <div className="fixed inset-0 bg-red-600 z-[150] flex flex-col items-center justify-center p-8 text-center animate-fade-in">
    <div className="w-24 h-24 bg-white rounded-full flex items-center justify-center mb-6 animate-pulse">
      <AlertTriangle size={48} className="text-red-600" />
    </div>
    <h1 className="text-4xl font-black text-white mb-4 tracking-tighter">EMERGENCY ALERT</h1>
    <p className="text-white/90 text-lg font-bold mb-8">
      Your input suggests a life-threatening condition. AI analysis is not sufficient.
    </p>
    <a href="tel:911" className="w-full bg-white text-red-600 py-6 rounded-[24px] font-black text-xl flex items-center justify-center gap-3 shadow-xl mb-4">
      <Phone size={24} /> CALL 911 NOW
    </a>
    <button onClick={onDismiss} className="text-white/70 text-sm font-bold underline decoration-2 underline-offset-4">
      I am safe, continue anyway
    </button>
  </div>
);

// --- PDF Generation Helper ---
const generateMedicalReport = (data: any, type: 'symptom' | 'wound' | 'mood') => {
    let title = "Medical Report";
    if (type === 'symptom') title = "Symptom Analysis Report";
    if (type === 'wound') title = "Dermatological Scan Report";
    if (type === 'mood') title = "Wellness & Fatigue Insight";

    const reportContent = `
      <html>
        <head>
          <title>Medi-Mirror Report</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; line-height: 1.5; }
            .header { border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
            h1 { color: #2563eb; font-size: 24px; margin: 0; }
            .meta { color: #64748b; font-size: 14px; margin-top: 5px; }
            .section { background: #f8fafc; padding: 25px; border-radius: 12px; margin-bottom: 20px; border: 1px solid #e2e8f0; }
            h2 { font-size: 16px; margin-top: 0; margin-bottom: 15px; color: #0f172a; text-transform: uppercase; letter-spacing: 0.05em; }
            p { margin: 0 0 10px 0; }
            .tag { display: inline-block; padding: 4px 8px; background: #e2e8f0; border-radius: 4px; font-size: 12px; font-weight: bold; margin-right: 5px; }
            .warning { color: #dc2626; font-weight: bold; font-size: 12px; margin-top: 40px; text-align: center; padding: 20px; background: #fef2f2; border-radius: 8px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${title}</h1>
            <div class="meta">Generated by Medi-Mirror AI • ${new Date().toLocaleString()}</div>
          </div>

          ${type === 'symptom' ? `
            <div class="section">
              <h2>Primary Condition</h2>
              <p style="font-size: 18px; font-weight: bold;">${data.conditions?.[0]?.name || "Unspecified"}</p>
              <p>${data.explanation}</p>
              <div style="margin-top: 10px;">
                <span class="tag">Severity: ${data.conditions?.[0]?.severity}</span>
                <span class="tag">Confidence: ${data.conditions?.[0]?.probability}</span>
              </div>
            </div>
            <div class="section">
              <h2>Treatment Plan</h2>
              <p>${data.treatment}</p>
              <p><strong>Recommended Specialist:</strong> ${data.specialistType}</p>
            </div>
            <div class="section">
              <h2>Suggested OTC Meds</h2>
              <p>${data.suggestedMedicines?.join(', ')}</p>
            </div>
          ` : ''}

          ${type === 'wound' ? `
            <div class="section">
              <h2>Scan Results</h2>
              <p style="font-size: 18px; font-weight: bold;">${data.conditionName}</p>
              <p>${data.description}</p>
            </div>
            <div class="section">
              <h2>Risk Analysis</h2>
              <p><strong>Infection Probability:</strong> ${data.infectionProbability}</p>
              <p><strong>Severity:</strong> ${data.severity}</p>
              <p><strong>Healing Stage:</strong> ${data.healingStage}</p>
            </div>
            <div class="section">
              <h2>Care Advice</h2>
              <p>${data.advice}</p>
            </div>
          ` : ''}
          
           ${type === 'mood' ? `
            <div class="section">
              <h2>Wellness Indicators</h2>
              <p><strong>Fatigue Level:</strong> ${data.fatigueLevel}</p>
              <p><strong>Stress Level:</strong> ${data.stressLevel}</p>
              <p><strong>Observed Signs:</strong> ${data.physicalSigns?.join(', ')}</p>
            </div>
            <div class="section">
              <h2>AI Insight</h2>
              <p>${data.insight}</p>
            </div>
          ` : ''}

          <div class="warning">
            DISCLAIMER: This report is generated by an Artificial Intelligence system for informational purposes only. 
            It is NOT a medical diagnosis. Do not use this for emergency situations. Always consult a licensed physician.
          </div>
          <script>window.print();</script>
        </body>
      </html>
    `;
    
    const win = window.open('', '_blank');
    if (win) {
      win.document.write(reportContent);
      win.document.close();
    }
};

// --- Tool 4: Medical Grade Vitals Monitor (rPPG & Resp) ---
const VitalsMonitor: React.FC = () => {
    const videoRef = useRef<HTMLVideoElement>(null);
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const [isActive, setIsActive] = useState(false);
    const [bpm, setBpm] = useState<number | null>(null);
    const [rr, setRr] = useState<number | null>(null); // Respiratory Rate
    const [progress, setProgress] = useState(0);
    const [status, setStatus] = useState("Align Face");
    
    // Pulse Graph Data (for visualization)
    const [pulseData, setPulseData] = useState<number[]>(new Array(50).fill(50));
    const [breathData, setBreathData] = useState<number[]>(new Array(50).fill(50));

    // Signal Processing Refs
    const signalRef = useRef({
        greenHistory: [] as number[],
        startTime: 0,
        frameCount: 0
    });

    const startScan = async () => {
        try {
            const stream = await navigator.mediaDevices.getUserMedia({ 
                video: { facingMode: 'user', width: {ideal: 640}, height: {ideal: 480}, frameRate: {ideal: 30} } 
            });
            if (videoRef.current) {
                videoRef.current.srcObject = stream;
                videoRef.current.play();
            }
            setIsActive(true);
            setStatus("Detecting Skin Tone...");
            signalRef.current = { greenHistory: [], startTime: Date.now(), frameCount: 0 };
            processFrame();
        } catch (e) {
            alert("Camera needed for vitals scan.");
        }
    };

    const stopScan = () => {
        const stream = videoRef.current?.srcObject as MediaStream;
        stream?.getTracks().forEach(t => t.stop());
        setIsActive(false);
        setProgress(0);
        setBpm(null);
        setRr(null);
    };

    const processFrame = () => {
        if (!isActive || !videoRef.current || !canvasRef.current) return;
        const ctx = canvasRef.current.getContext('2d', { willReadFrequently: true });
        if (!ctx) return;

        // Draw video to canvas
        const vid = videoRef.current;
        if (vid.videoWidth === 0) {
             requestAnimationFrame(processFrame);
             return;
        }

        canvasRef.current.width = 100;
        canvasRef.current.height = 100;
        
        // Extract ROI (Forehead area approx - Center Top)
        // Simple approximation: Center 20% width, Top 20-40% height
        const sx = vid.videoWidth * 0.4;
        const sy = vid.videoHeight * 0.2;
        const sw = vid.videoWidth * 0.2;
        const sh = vid.videoHeight * 0.15;

        ctx.drawImage(vid, sx, sy, sw, sh, 0, 0, 50, 50);
        const frame = ctx.getImageData(0, 0, 50, 50);
        const data = frame.data;

        // 1. Extract Green Channel (Hemoglobin Absorption Peak)
        let gSum = 0;
        for (let i = 0; i < data.length; i += 4) {
            gSum += data[i + 1]; // Green
        }
        const gAvg = gSum / (data.length / 4);

        // Store raw signal
        signalRef.current.greenHistory.push(gAvg);
        if (signalRef.current.greenHistory.length > 300) { // Keep 10s buffer @ 30fps
            signalRef.current.greenHistory.shift(); 
        }

        // 2. Real-time Visualization (High Pass Filtered for Graph)
        const buffer = signalRef.current.greenHistory;
        if (buffer.length > 30) {
             // Simple DC removal
             const window = buffer.slice(-30);
             const mean = window.reduce((a,b)=>a+b,0) / window.length;
             const val = gAvg - mean;
             
             // Update Pulse Graph
             setPulseData(prev => [...prev.slice(1), 50 + (val * 5)]);

             // Update Breath Graph (Low Frequency Component)
             // Breath modulates the amplitude of the pulse (RSA) or baseline wander
             // We use a much slower moving average to estimate breath wave
             const breathWindow = buffer.slice(-150); // 5 sec window
             const breathMean = breathWindow.reduce((a,b)=>a+b,0) / breathWindow.length;
             // Normalize for display
             setBreathData(prev => [...prev.slice(1), 50 + ((gAvg - breathMean) * 2)]);
        }

        // 3. Progress Update
        const elapsed = Date.now() - signalRef.current.startTime;
        const p = Math.min(100, (elapsed / 15000) * 100); // 15s scan
        setProgress(p);

        if (p < 20) setStatus("Calibrating...");
        else if (p < 100) setStatus("Hold Still...");
        else if (isActive) {
            calculateVitals();
            setIsActive(false);
            return; // Stop loop
        }

        requestAnimationFrame(processFrame);
    };

    const calculateVitals = () => {
        const signal = signalRef.current.greenHistory;
        if (signal.length < 150) {
            setStatus("Scan Failed. Try Again.");
            return;
        }

        // --- Heart Rate Logic (Bandpass + Zero Crossing) ---
        // 1. Detrend (Simple Difference)
        const detrended = [];
        for(let i=1; i<signal.length; i++) detrended.push(signal[i] - signal[i-1]);

        // 2. Smoothing (Moving Average) to remove high freq noise
        const smoothed = [];
        for(let i=2; i<detrended.length-2; i++) {
            smoothed.push((detrended[i-2] + detrended[i-1] + detrended[i] + detrended[i+1] + detrended[i+2])/5);
        }

        // 3. Peak Detection (Simple sign change for zero crossing of derivative approx)
        let peaks = 0;
        for(let i=1; i<smoothed.length; i++) {
            if (smoothed[i] > 0 && smoothed[i-1] <= 0) peaks++;
        }
        
        // Calculate BPM based on duration
        const durationSec = signal.length / 30; // Approx 30fps
        const calculatedBpm = Math.round((peaks / durationSec) * 60);

        // --- Respiratory Rate Logic (Signal Amplitude Modulation / RSA) ---
        // Breathing modulates the heart rate (faster on inhale, slower on exhale).
        // We look for low frequency waves in the raw signal baseline.
        // Downsample to ~5Hz to isolate breath
        const downsampled = [];
        for(let i=0; i<signal.length; i+=6) downsampled.push(signal[i]);
        
        // Count peaks in baseline (Low freq)
        let breaths = 0;
        // Simple directional change counter
        let direction = 0; // 1 up, -1 down
        for(let i=1; i<downsampled.length; i++) {
             if (downsampled[i] > downsampled[i-1]) {
                 if (direction === -1) breaths++;
                 direction = 1;
             } else {
                 direction = -1;
             }
        }
        // Normalize (Breaths usually 12-20 per min)
        const calculatedRr = Math.round((breaths / 2) * (60 / durationSec)); // Divide by 2 (up+down = 1 breath)

        setBpm(Math.min(180, Math.max(40, calculatedBpm)));
        setRr(Math.min(30, Math.max(8, calculatedRr)));
        setStatus("Scan Complete");
        const stream = videoRef.current?.srcObject as MediaStream;
        stream?.getTracks().forEach(t => t.stop());
    };

    const renderGraph = (data: number[], color: string) => {
       const points = data.map((val, i) => {
           const y = 50 - ((val - 50)); // Center at 50
           const x = (i / (data.length - 1)) * 100;
           return `${x},${Math.max(0, Math.min(100, y))}`;
       }).join(' ');
       return (
           <svg viewBox="0 0 100 100" className="w-full h-full overflow-visible" preserveAspectRatio="none">
               <polyline points={points} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" />
           </svg>
       );
    };

    return (
        <div className="h-full flex flex-col relative animate-fade-in overflow-y-auto pb-32">
            {!isActive && !bpm ? (
                <div className="p-6 flex-1 flex flex-col space-y-6">
                    <div className="space-y-2">
                        <h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tighter">Vitals Monitor</h2>
                        <p className="text-slate-500 text-sm font-medium">Medical-grade rPPG Heart & Respiratory Scan.</p>
                    </div>
                    
                    <div className="bg-slate-100 dark:bg-slate-800 rounded-[32px] p-8 text-center space-y-6">
                         <div className="w-24 h-24 mx-auto bg-white dark:bg-slate-700 rounded-full flex items-center justify-center text-blue-500">
                             <ScanFace size={48} />
                         </div>
                         <div className="text-left space-y-4">
                            <div className="flex items-start gap-3">
                                <span className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center text-xs font-bold shrink-0">1</span>
                                <p className="text-sm text-slate-600 dark:text-slate-300">Position your face in the camera frame.</p>
                            </div>
                            <div className="flex items-start gap-3">
                                <span className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center text-xs font-bold shrink-0">2</span>
                                <p className="text-sm text-slate-600 dark:text-slate-300">Hold steady for 15 seconds. Do not talk.</p>
                            </div>
                            <div className="flex items-start gap-3">
                                <span className="w-6 h-6 rounded-full bg-blue-600 text-white flex items-center justify-center text-xs font-bold shrink-0">3</span>
                                <p className="text-sm text-slate-600 dark:text-slate-300">We analyze skin color changes (rPPG) to detect pulse.</p>
                            </div>
                         </div>
                    </div>

                    <button onClick={startScan} className="w-full bg-blue-600 text-white py-5 rounded-[24px] font-black text-lg shadow-xl shadow-blue-600/20">
                        Start Scan
                    </button>
                </div>
            ) : isActive ? (
                <div className="flex-1 bg-black relative flex flex-col">
                    <video ref={videoRef} className="absolute inset-0 w-full h-full object-cover opacity-60" playsInline muted></video>
                    <canvas ref={canvasRef} className="hidden"></canvas>
                    
                    <div className="absolute inset-0 z-10 flex flex-col items-center justify-center p-6">
                        {/* ROI Guide */}
                        <div className="w-64 h-80 border-4 border-white/30 rounded-[100px] mb-8 relative">
                             <div className="absolute top-0 left-1/2 -translate-x-1/2 -mt-1 w-1 h-4 bg-green-500"></div>
                             <div className="absolute bottom-0 left-1/2 -translate-x-1/2 -mb-1 w-1 h-4 bg-green-500"></div>
                             <div className="absolute top-1/2 left-0 -translate-y-1/2 -ml-1 w-4 h-1 bg-green-500"></div>
                             <div className="absolute top-1/2 right-0 -translate-y-1/2 -mr-1 w-4 h-1 bg-green-500"></div>
                        </div>
                        
                        <h3 className="text-2xl font-black text-white animate-pulse mb-8">{status}</h3>
                        
                        <div className="w-full max-w-xs space-y-4">
                            {/* Graphs */}
                            <div className="h-16 bg-black/50 backdrop-blur-md rounded-xl border border-white/10 relative overflow-hidden">
                                <div className="absolute top-2 left-2 text-[10px] text-red-400 font-bold uppercase">Pulse Wave</div>
                                {renderGraph(pulseData, '#ef4444')}
                            </div>
                            <div className="h-16 bg-black/50 backdrop-blur-md rounded-xl border border-white/10 relative overflow-hidden">
                                <div className="absolute top-2 left-2 text-[10px] text-blue-400 font-bold uppercase">Respiration</div>
                                {renderGraph(breathData, '#3b82f6')}
                            </div>
                        </div>

                        {/* Progress */}
                        <div className="absolute bottom-10 left-6 right-6">
                            <div className="h-2 bg-white/20 rounded-full overflow-hidden">
                                <div className="h-full bg-green-500 transition-all duration-300 ease-linear" style={{ width: `${progress}%` }}></div>
                            </div>
                        </div>
                    </div>
                </div>
            ) : (
                <div className="p-6 flex-1 flex flex-col space-y-6">
                    <div className="flex justify-between items-center">
                         <h2 className="text-2xl font-black text-slate-900 dark:text-white">Results</h2>
                         <button onClick={() => setBpm(null)} className="text-sm font-bold text-blue-600">Scan Again</button>
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                        <div className="bg-red-50 dark:bg-red-900/20 p-6 rounded-[32px] flex flex-col items-center justify-center text-center">
                             <div className="mb-2 text-red-500"><Heart size={32} fill="currentColor" /></div>
                             <div className="text-4xl font-black text-slate-900 dark:text-white">{bpm}</div>
                             <div className="text-xs font-bold text-red-500 uppercase tracking-widest">BPM</div>
                        </div>
                        <div className="bg-blue-50 dark:bg-blue-900/20 p-6 rounded-[32px] flex flex-col items-center justify-center text-center">
                             <div className="mb-2 text-blue-500"><Wind size={32} /></div>
                             <div className="text-4xl font-black text-slate-900 dark:text-white">{rr}</div>
                             <div className="text-xs font-bold text-blue-500 uppercase tracking-widest">Breaths/Min</div>
                        </div>
                    </div>
                    
                    <div className="bg-slate-100 dark:bg-slate-800 p-6 rounded-[24px]">
                        <h4 className="font-bold text-slate-900 dark:text-white mb-2">Analysis</h4>
                        <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
                           Your resting heart rate is {bpm && bpm < 60 ? 'athletic' : bpm && bpm > 100 ? 'elevated' : 'normal'}. 
                           Respiration rate is within {rr && rr >= 12 && rr <= 20 ? 'healthy' : 'variable'} range.
                        </p>
                    </div>
                </div>
            )}
        </div>
    );
};

// --- Tool 1: Symptom Checker ---
const SymptomChecker: React.FC = () => {
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<SymptomAnalysis | null>(null);
  const [emergencyTriggered, setEmergencyTriggered] = useState(false);
  const navigate = useNavigate();

  const commonSymptoms = [
    { label: 'Headache', icon: <Brain size={14} /> },
    { label: 'Fever', icon: <Thermometer size={14} /> },
    { label: 'Cough', icon: <Wind size={14} /> },
    { label: 'Nausea', icon: <Activity size={14} /> },
    { label: 'Fatigue', icon: <Clock size={14} /> },
  ];

  const handleAnalyze = async () => {
    if (!input.trim()) return;
    if (checkEmergencyKeywords(input)) {
       setEmergencyTriggered(true);
       return;
    }
    setLoading(true);
    try {
      const data = await analyzeSymptoms(input);
      setResult(data);
    } catch (e) {
      alert("Analysis failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="h-full flex flex-col relative overflow-hidden animate-fade-in">
      {emergencyTriggered && <EmergencyOverlay onDismiss={() => setEmergencyTriggered(false)} />}
      {loading && <LoadingOverlay text="Analyzing Vitals" />}
      
      {!result ? (
        <div className="flex-1 flex flex-col p-6 space-y-6 overflow-y-auto pb-32">
          <div className="space-y-2">
            <h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tighter">Diagnostic Lab</h2>
            <p className="text-slate-500 text-sm font-medium">Describe your symptoms to our medical AI.</p>
          </div>

          <div className="bg-white dark:bg-slate-900 rounded-[32px] p-6 shadow-sm border border-slate-100 dark:border-slate-800 space-y-4">
            <textarea 
              value={input}
              onChange={(e) => setInput(e.target.value)}
              className="w-full h-32 bg-transparent focus:outline-none resize-none placeholder:text-slate-300 dark:placeholder:text-slate-600 font-bold text-lg text-slate-900 dark:text-white"
              placeholder="e.g., I've had a recurring migraine since this morning..."
            />
            <div className="flex flex-wrap gap-2">
              {commonSymptoms.map((s, idx) => (
                <button
                  key={idx}
                  onClick={() => setInput(p => p ? `${p}, ${s.label}` : s.label)}
                  className="px-3 py-1.5 bg-slate-50 dark:bg-slate-800 rounded-lg text-xs font-bold text-slate-600 dark:text-slate-400 flex items-center gap-1.5 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors"
                >
                  {s.icon} {s.label}
                </button>
              ))}
            </div>
          </div>

          <button 
            onClick={handleAnalyze}
            disabled={!input}
            className="w-full bg-slate-900 dark:bg-blue-600 text-white py-5 rounded-[24px] font-black text-lg flex items-center justify-center gap-3 active:scale-[0.98] transition-all disabled:opacity-50"
          >
            <Search size={22} /> Start Analysis
          </button>
        </div>
      ) : (
        <div className="flex-1 flex flex-col p-6 space-y-6 overflow-y-auto pb-32">
          <div className="flex justify-between items-center">
             <button onClick={() => setResult(null)} className="p-2 bg-slate-100 dark:bg-slate-800 rounded-full text-slate-600 dark:text-slate-400">
               <ArrowLeft size={20} />
             </button>
             <button onClick={() => generateMedicalReport(result, 'symptom')} className="flex items-center gap-2 text-blue-600 dark:text-blue-400 text-xs font-black uppercase tracking-wider">
               <Download size={16} /> Save PDF
             </button>
          </div>

          <div className={`p-6 rounded-[32px] ${result.seeDoctor ? 'bg-red-50 dark:bg-red-900/20 text-red-900 dark:text-red-100' : 'bg-green-50 dark:bg-green-900/20 text-green-900 dark:text-green-100'}`}>
             <div className="flex items-center gap-3 mb-2">
                {result.seeDoctor ? <AlertTriangle size={24} /> : <CheckCircle size={24} />}
                <h3 className="text-lg font-black">{result.conditions[0]?.name}</h3>
             </div>
             <p className="text-sm font-medium opacity-90">{result.explanation}</p>
          </div>

          <div className="space-y-4">
            <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest">Recommended Plan</h4>
            <div className="bg-white dark:bg-slate-900 p-5 rounded-[24px] border border-slate-100 dark:border-slate-800 space-y-4">
               <div>
                 <p className="text-[10px] font-bold text-slate-400 uppercase mb-1">Treatment</p>
                 <p className="font-bold text-slate-800 dark:text-slate-200 text-sm">{result.treatment}</p>
               </div>
               <div>
                 <p className="text-[10px] font-bold text-slate-400 uppercase mb-1">Meds (OTC)</p>
                 <div className="flex flex-wrap gap-2">
                    {result.suggestedMedicines.map((m, i) => (
                      <span key={i} className="px-3 py-1 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-lg text-xs font-bold">{m}</span>
                    ))}
                 </div>
               </div>
            </div>
          </div>
          
          <button onClick={() => navigate(`/doctors?q=${result.specialistType}`)} className="w-full bg-blue-600 text-white py-4 rounded-[20px] font-bold flex items-center justify-center gap-2">
             Find {result.specialistType} <ChevronRight size={18} />
          </button>
        </div>
      )}
    </div>
  );
};

// --- Tool 2: Wound Scanner ---
const WoundScanner: React.FC = () => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [image, setImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<WoundAnalysis | null>(null);
  const [cameraActive, setCameraActive] = useState(false);

  const startCamera = async () => {
    setCameraActive(true);
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
      if (videoRef.current) videoRef.current.srcObject = stream;
    } catch (e) { alert("Camera access denied"); setCameraActive(false); }
  };

  const capture = () => {
    if (!videoRef.current) return;
    const canvas = document.createElement('canvas');
    canvas.width = videoRef.current.videoWidth;
    canvas.height = videoRef.current.videoHeight;
    canvas.getContext('2d')?.drawImage(videoRef.current, 0, 0);
    setImage(canvas.toDataURL('image/jpeg'));
    setCameraActive(false);
    const stream = videoRef.current.srcObject as MediaStream;
    stream?.getTracks().forEach(t => t.stop());
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => setImage(reader.result as string);
      reader.readAsDataURL(file);
    }
  };

  const analyze = async () => {
    if (!image) return;
    setLoading(true);
    try {
      const data = await analyzeWound(image);
      setResult(data);
    } catch (e) { alert("Analysis failed."); } 
    finally { setLoading(false); }
  };

  return (
    <div className="h-full flex flex-col relative animate-fade-in overflow-y-auto pb-32">
      {loading && <LoadingOverlay text="Scanning Tissue" />}
      
      {!result ? (
        <div className="p-6 flex-1 flex flex-col space-y-6">
           <div className="space-y-2">
            <h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tighter">Wound Scanner</h2>
            <p className="text-slate-500 text-sm font-medium">Analyze injuries, rashes, or burns instantly.</p>
           </div>

           <div className="flex-1 bg-slate-100 dark:bg-slate-800 rounded-[32px] overflow-hidden relative flex flex-col items-center justify-center min-h-[300px]">
              {cameraActive ? (
                <video ref={videoRef} autoPlay playsInline className="w-full h-full object-cover" />
              ) : image ? (
                <img src={image} className="w-full h-full object-cover" />
              ) : (
                <div className="text-center p-6">
                   <div className="w-16 h-16 bg-white dark:bg-slate-700 rounded-full flex items-center justify-center mx-auto mb-4 text-slate-400">
                     <Camera size={24} />
                   </div>
                   <p className="text-slate-400 font-bold text-sm">No Image Selected</p>
                </div>
              )}
              
              {cameraActive && (
                <button onClick={capture} className="absolute bottom-6 w-16 h-16 bg-white rounded-full border-4 border-slate-200 flex items-center justify-center shadow-lg active:scale-90 transition-transform">
                   <div className="w-12 h-12 bg-red-500 rounded-full"></div>
                </button>
              )}
           </div>

           {!cameraActive && (
             <div className="grid grid-cols-2 gap-4">
                <button onClick={startCamera} className="py-4 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-[20px] font-black flex items-center justify-center gap-2">
                  <Camera size={18} /> Camera
                </button>
                <button onClick={() => fileInputRef.current?.click()} className="py-4 bg-white dark:bg-slate-800 text-slate-900 dark:text-white border border-slate-200 dark:border-slate-700 rounded-[20px] font-black flex items-center justify-center gap-2">
                  <ImageIcon size={18} /> Gallery
                </button>
                <input type="file" ref={fileInputRef} hidden accept="image/*" onChange={handleFileUpload} />
             </div>
           )}

           {image && !cameraActive && (
             <button onClick={analyze} className="w-full bg-blue-600 text-white py-5 rounded-[24px] font-black text-lg shadow-xl shadow-blue-600/20">
               Analyze Image
             </button>
           )}
        </div>
      ) : (
        <div className="p-6 flex-1 flex flex-col space-y-6">
           <div className="flex justify-between items-center">
             <button onClick={() => setResult(null)} className="p-2 bg-slate-100 dark:bg-slate-800 rounded-full text-slate-600 dark:text-slate-400"><ArrowLeft size={20} /></button>
             <button onClick={() => generateMedicalReport(result, 'wound')} className="text-xs font-black text-blue-600 uppercase">Save PDF</button>
           </div>
           
           <div className={`p-6 rounded-[32px] ${result.urgentCareNeeded ? 'bg-red-50 text-red-900' : 'bg-orange-50 text-orange-900'}`}>
              <h3 className="text-2xl font-black mb-2">{result.conditionName}</h3>
              <p className="text-sm font-medium opacity-90">{result.description}</p>
              <div className="flex gap-2 mt-4">
                 <span className="px-3 py-1 bg-white/50 rounded-lg text-xs font-bold">Infection Risk: {result.infectionProbability}</span>
                 <span className="px-3 py-1 bg-white/50 rounded-lg text-xs font-bold">Severity: {result.severity}</span>
              </div>
           </div>

           <div className="bg-white dark:bg-slate-900 p-6 rounded-[32px] border border-slate-100 dark:border-slate-800">
              <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-3">Care Instructions</h4>
              <p className="text-slate-800 dark:text-slate-200 font-medium leading-relaxed">{result.advice}</p>
           </div>
        </div>
      )}
    </div>
  );
};

// --- Tool 3: Daily Mirror Check (New Feature) ---
const MirrorCheck: React.FC = () => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState<MoodAnalysis | null>(null);
  const [cameraOn, setCameraOn] = useState(false);

  const startMirror = async () => {
    setCameraOn(true);
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user' } });
      if (videoRef.current) videoRef.current.srcObject = stream;
    } catch (e) { alert("Camera denied"); }
  };

  const scanFace = async () => {
    if (!videoRef.current) return;
    setAnalyzing(true);
    const canvas = document.createElement('canvas');
    canvas.width = videoRef.current.videoWidth;
    canvas.height = videoRef.current.videoHeight;
    canvas.getContext('2d')?.drawImage(videoRef.current, 0, 0);
    const base64 = canvas.toDataURL('image/jpeg');
    
    // Stop camera
    const stream = videoRef.current.srcObject as MediaStream;
    stream?.getTracks().forEach(t => t.stop());
    setCameraOn(false);

    try {
      const data = await analyzeMood(base64);
      setResult(data);
    } catch (e) { alert("Scan failed."); } 
    finally { setAnalyzing(false); }
  };

  return (
    <div className="h-full flex flex-col relative animate-fade-in overflow-y-auto pb-32">
      {analyzing && <LoadingOverlay text="Analyzing Facial Cues" />}

      {!result ? (
        <div className="p-6 flex-1 flex flex-col space-y-6">
           <div className="space-y-2">
             <h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tighter">Daily Mirror Check</h2>
             <p className="text-slate-500 text-sm font-medium">AI analysis of fatigue, stress, and wellness.</p>
           </div>

           <div className="flex-1 bg-black rounded-[40px] overflow-hidden relative shadow-2xl">
              {!cameraOn ? (
                <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-900 text-white p-8 text-center">
                   <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center mb-6">
                      <Sparkles className="text-purple-400" size={32} />
                   </div>
                   <h3 className="text-xl font-bold mb-2">Morning Scan</h3>
                   <p className="text-slate-400 text-sm">Center your face in good lighting. We'll analyze pallor, eye fatigue, and expression.</p>
                   <button onClick={startMirror} className="mt-8 px-8 py-3 bg-white text-black rounded-xl font-black text-sm uppercase tracking-widest">
                     Open Mirror
                   </button>
                </div>
              ) : (
                <>
                  <video ref={videoRef} autoPlay playsInline className="w-full h-full object-cover transform scale-x-[-1]" />
                  <div className="absolute inset-0 border-[6px] border-white/20 rounded-[40px] pointer-events-none"></div>
                  <div className="absolute bottom-8 left-0 right-0 flex justify-center z-20">
                    <button onClick={scanFace} className="w-20 h-20 bg-white rounded-full border-4 border-purple-200 flex items-center justify-center shadow-lg active:scale-90 transition-transform">
                      <Zap size={32} className="text-purple-600 fill-purple-600" />
                    </button>
                  </div>
                </>
              )}
           </div>
        </div>
      ) : (
        <div className="p-6 flex-1 flex flex-col space-y-6">
           <div className="flex justify-between items-center">
             <button onClick={() => setResult(null)} className="p-2 bg-slate-100 dark:bg-slate-800 rounded-full"><ArrowLeft size={20} /></button>
             <button onClick={() => generateMedicalReport(result, 'mood')} className="text-xs font-black text-blue-600 uppercase">Save Report</button>
           </div>

           <div className="text-center space-y-2">
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">Wellness Score</span>
              <div className="text-6xl font-black text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-600">
                {result.wellnessScore}<span className="text-2xl text-slate-300">/10</span>
              </div>
           </div>

           <div className="grid grid-cols-2 gap-4">
              <div className="bg-white dark:bg-slate-900 p-5 rounded-[24px] border border-slate-100 dark:border-slate-800">
                 <p className="text-[10px] font-black text-slate-400 uppercase mb-2">Fatigue</p>
                 <p className={`text-xl font-black ${result.fatigueLevel === 'High' ? 'text-red-500' : 'text-green-500'}`}>{result.fatigueLevel}</p>
              </div>
              <div className="bg-white dark:bg-slate-900 p-5 rounded-[24px] border border-slate-100 dark:border-slate-800">
                 <p className="text-[10px] font-black text-slate-400 uppercase mb-2">Stress</p>
                 <p className={`text-xl font-black ${result.stressLevel === 'High' ? 'text-red-500' : 'text-green-500'}`}>{result.stressLevel}</p>
              </div>
           </div>

           <div className="bg-purple-50 dark:bg-purple-900/10 p-6 rounded-[32px]">
              <h3 className="text-purple-900 dark:text-purple-300 font-bold mb-2 flex items-center gap-2">
                <Leaf size={18} /> Insight
              </h3>
              <p className="text-purple-800 dark:text-purple-200 text-sm font-medium leading-relaxed">{result.insight}</p>
           </div>
           
           <div>
             <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-3">Observed Signs</h4>
             <div className="flex flex-wrap gap-2">
               {result.physicalSigns.map((sign, i) => (
                 <span key={i} className="px-4 py-2 bg-slate-100 dark:bg-slate-800 rounded-xl text-xs font-bold text-slate-600 dark:text-slate-300">
                   {sign}
                 </span>
               ))}
             </div>
           </div>
        </div>
      )}
    </div>
  );
};

// --- Chat ---
export const Chat: React.FC = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    { id: '1', role: 'ai', text: 'Hi! I am Medi. How can I help you today?', timestamp: new Date() }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);

  const send = async () => {
    if (!input.trim()) return;
    const userMsg: ChatMessage = { id: Date.now().toString(), role: 'user', text: input, timestamp: new Date() };
    setMessages(p => [...p, userMsg]);
    setInput('');
    setLoading(true);

    if (checkEmergencyKeywords(userMsg.text)) {
      navigate('/emergency');
      return;
    }

    try {
      const historyMsg = messages.map(m => ({ role: m.role === 'ai' ? 'model' : 'user', parts: [{ text: m.text }] }));
      const response = await chatWithMedi(historyMsg, userMsg.text);
      setMessages(p => [...p, { id: Date.now().toString(), role: 'ai', text: response || "I'm not sure.", timestamp: new Date() }]);
    } catch (e) {
      setMessages(p => [...p, { id: Date.now().toString(), role: 'ai', text: "Connection error. Please try again.", timestamp: new Date() }]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-screen bg-slate-50 dark:bg-slate-950">
       <div className="p-4 bg-white dark:bg-slate-900 border-b border-slate-100 dark:border-slate-800 sticky top-0 z-10 flex items-center gap-3">
          <button onClick={() => navigate(-1)} className="p-2 bg-slate-100 dark:bg-slate-800 rounded-full"><ArrowLeft size={20} /></button>
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
            <h1 className="font-black text-slate-900 dark:text-white">Medi Assistant</h1>
          </div>
       </div>

       <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {messages.map(m => (
            <div key={m.id} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
               <div className={`max-w-[80%] p-4 rounded-2xl text-sm font-medium leading-relaxed ${
                 m.role === 'user' 
                   ? 'bg-blue-600 text-white rounded-br-none' 
                   : 'bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-200 border border-slate-100 dark:border-slate-800 rounded-bl-none shadow-sm'
               }`}>
                  {m.text}
               </div>
            </div>
          ))}
          {loading && <div className="text-slate-400 text-xs font-bold ml-4 animate-pulse">Medi is typing...</div>}
          <div ref={bottomRef}></div>
       </div>

       <div className="p-4 bg-white dark:bg-slate-900 border-t border-slate-100 dark:border-slate-800">
          <div className="flex gap-2">
             <input 
               value={input}
               onChange={e => setInput(e.target.value)}
               onKeyDown={e => e.key === 'Enter' && send()}
               placeholder="Ask anything..."
               className="flex-1 bg-slate-100 dark:bg-slate-800 rounded-xl px-4 py-3 outline-none font-bold text-slate-900 dark:text-white"
             />
             <button onClick={send} disabled={!input || loading} className="p-3 bg-blue-600 text-white rounded-xl disabled:opacity-50">
               <Send size={20} />
             </button>
          </div>
       </div>
    </div>
  );
};

// --- Main Wrapper ---
export const ToolWrapper: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'symptom' | 'wound' | 'mirror' | 'vitals'>('symptom');
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const mode = params.get('mode');
    if (mode === 'wound') setActiveTab('wound');
    if (mode === 'mirror') setActiveTab('mirror');
    if (mode === 'vitals') setActiveTab('vitals');
  }, [location]);

  const tabs = [
    { id: 'symptom', label: 'Symptoms', icon: Activity },
    { id: 'wound', label: 'Scanner', icon: Camera },
    { id: 'mirror', label: 'Mirror', icon: Smile },
    { id: 'vitals', label: 'Vitals', icon: ScanFace },
  ];

  return (
    <div className="h-screen flex flex-col bg-slate-50 dark:bg-slate-950 transition-colors">
      <div className="px-6 pt-6 pb-2 sticky top-0 z-10 bg-slate-50/90 dark:bg-slate-950/90 backdrop-blur-sm">
        <div className="flex justify-between items-center mb-4">
           <h1 className="text-2xl font-black text-slate-900 dark:text-white">Health Tools</h1>
           <button onClick={() => navigate('/chat')} className="p-2 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-full">
             <MessageSquare size={20} />
           </button>
        </div>
        <div className="flex p-1 bg-slate-200 dark:bg-slate-800 rounded-2xl">
           {tabs.map(t => (
             <button
               key={t.id}
               onClick={() => setActiveTab(t.id as any)}
               className={`flex-1 py-3 rounded-xl text-xs font-black uppercase tracking-widest flex items-center justify-center gap-2 transition-all ${
                 activeTab === t.id 
                   ? 'bg-white dark:bg-slate-700 text-slate-900 dark:text-white shadow-md' 
                   : 'text-slate-500 dark:text-slate-400'
               }`}
             >
               <t.icon size={14} /> <span className="hidden sm:inline">{t.label}</span>
             </button>
           ))}
        </div>
      </div>

      <div className="flex-1 overflow-hidden relative">
         {activeTab === 'symptom' && <SymptomChecker />}
         {activeTab === 'wound' && <WoundScanner />}
         {activeTab === 'mirror' && <MirrorCheck />}
         {activeTab === 'vitals' && <VitalsMonitor />}
      </div>
    </div>
  );
};
